apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sops-operator.fullname" . }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    {{- include "sops-operator.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "sops-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.secret.stringData .Values.pod.annotations }}
      annotations:
      {{- if .Values.secret.stringData }}
        sops-operator/secret-hash: "{{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}"
      {{- end }}
      {{- with .Values.pod.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "sops-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sops-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.gpg.enabled }}
      initContainers:
        - name: init-gpg
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          command:
            - sh
            - '-c'
            - >-
              gpg --batch --import /var/secrets/gpg-secrets/gpg-key-secret;
              gpg --import-ownertrust /var/secrets/gpg-secrets/gpg-ownertrust-secret;
              echo ${PASSPHRASE} | gpg --batch --always-trust --yes --passphrase-fd 0 --pinentry-mode=loopback -s
          env:
            - name: GNUPGHOME
              value: /var/secrets/gpg
            - name: PASSPHRASE
              valueFrom:
                secretKeyRef:
                  key: gpg-passphrase
                  name: {{ .Values.gpg.passphraseSecret }}
          volumeMounts:
          - mountPath: /var/secrets/gpg
            name: sops-gpg
          - mountPath: /var/secrets/gpg-secrets
            name: sops-operator-gpg-key-secret
          - mountPath: /var/secrets/gpg-secrets
            name: sops-operator-gpg-ownertrust-secret
      {{- end }}
      containers:
        - name: sops-operator
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.gpg.enabled }}
            - name: GNUPGHOME
              value: /var/secrets/gpg
            - name: PASSPHRASE
              valueFrom:
                secretKeyRef:
                  key: gpg-passphrase
                  name: {{ .Values.gpg.passphraseSecret }}
            {{- end }}
            - name: WATCH_NAMESPACE
              value: "{{ if .Values.rbac.clusterScoped }}{{ .Values.watchNamespace }}{{ else }}{{ .Release.Namespace }}{{ end }}"
          {{- with .Values.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if not .Values.secret.mountPath }}
          {{- if or .Values.secret.stringData .Values.secret.existingSecret }}
          envFrom:
            - secretRef:
                name: {{ include "sops-operator.secretName" . }}
          {{- end }}
          {{- end }}
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
            - name: http-readiness
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http-readiness
              path: /readyz
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.secret.mountPath }}
            - mountPath: {{ . }}
              name: secrets
              readOnly: true
            {{- end }}
            {{- if .Values.gpg.enabled }}
            - mountPath: /var/secrets/gpg
              name: sops-gpg
            {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      volumes:
        {{- with .Values.secret.mountPath }}
        - name: secrets
          secret:
            secretName: {{ include "sops-operator.secretName" $ }}
        {{- end }}
        {{- if .Values.gpg.enabled }}
        - name: sops-operator-gpg-key-secret
          secret:
            secretName: {{ .Values.gpg.keySecret }}
        - name: sops-operator-gpg-ownertrust-secret
          secret:
            secretName: {{ .Values.gpg.ownertrustSecret }}
        - name: sops-gpg
          emptyDir: {}
        {{- end }}
      
